spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name:  kakao
            client-id:  ${KAKAO_CLIENT_ID}
            client-secret:  ${KAKAO_CLIENT_SECRET}
            scope:  profile_nickname, profile_image, account_email
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            authorization-grant-type:  authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri:  https://kauth.kakao.com/oauth/authorize
            token-uri:  https://kauth.kakao.com/oauth/token
            user-info-uri:  https://kapi.kakao.com/v2/user/me
            user-name-attribute:  id

jwt:
  header: token
  issuer: was
  client-secret: ${JWT_SECRET}
  expiry-seconds: 6000

cloud:
  aws:
    credentials:
      accessKey:  ${AWS_ACCESS_KEY_ID}
      secretKey:  ${AWS_SECRET_ACCESS_KEY}
      instanceProfile: true
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false
